In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
usa_market = pd.read_csv('real-data/usa_n3538_m5993_yr2010.csv', index_col=0)
print(usa_market.shape)
usa_market.head()

(3538, 5993)

,AAL,AAWW,ADV,AIR,AIRI,AIRT,AJRD,ALGT,ALK,ARNC,...,VIA,VOD,VRTV,WCC,WLFC,WSO,WTRG,YGMZ,YORW,ZWS
Date,,,,,,,,,,,,,,,,,,,,,
2009-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04 00:00:00,4.496876,NaN,NaN,21.401571,39.339664,5.638029,NaN,40.233162,7.774136,NaN,...,NaN,11.630528,NaN,27.580000,14.77,32.134510,10.025703,NaN,11.277903,NaN
2010-01-05 00:00:00,5.005957,NaN,NaN,21.815735,39.339664,5.721555,NaN,41.632645,8.199961,NaN,...,NaN,11.545262,NaN,27.780001,14.56,31.254126,10.054380,NaN,11.133990,NaN
2010-01-06 00:00:00,4.798555,NaN,NaN,22.914175,39.339664,5.721555,NaN,41.691303,8.126390,NaN,...,NaN,11.454986,NaN,28.750000,14.17,31.467731,10.071585,NaN,10.800728,NaN
2010-01-07 00:00:00,4.939965,NaN,NaN,23.274321,39.339664,5.697690,NaN,41.573986,8.084030,NaN,...,NaN,11.239326,NaN,29.170000,14.01,31.953251,10.088791,NaN,10.770434,NaN

In [5]:
# NA analysis
# Check rows with only NA
print(usa_market.shape)
usa_market = usa_market[~usa_market.isnull().all(axis=1)]
n,m = usa_market.shape
print(usa_market.shape)
# Drop columns with more than 10% NA
usa_market = usa_market.dropna(thresh=n*0.99, axis=1)
n,m = usa_market.shape
print(usa_market.shape)
# Drop rows with more than 10% NA
usa_market = usa_market.dropna(thresh=m*0.99, axis=0)
n,m = usa_market.shape
print(usa_market.shape)
usa_market.loc[:, usa_market.isnull().any()].head()
# usa_market.isnull().sum()

(3538, 5993)
(3522, 5993)
(3522, 2440)
(3522, 2440)

,PACW,PTRS,IRWD,MESO,SGEN,GHL,CCF,SCU,SII,SLRC,...,NM,CHTR,AAIC,SAND,WMC,HEP,ACER,TAK,BSQR,VMW
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04 00:00:00,13.562780,4.974054,NaN,NaN,10.54,51.020618,9.947630,55.762394,NaN,NaN,...,47.649403,NaN,3.799236,NaN,21.314995,8.104968,583.349365,NaN,2.52,29.683350
2010-01-05 00:00:00,13.109385,5.608002,NaN,NaN,10.53,52.389797,9.752744,57.183880,NaN,NaN,...,50.039352,35.0,3.878787,NaN,21.314995,8.254497,565.760925,14.150663,2.75,30.827898
2010-01-06 00:00:00,13.141778,5.022819,NaN,NaN,10.82,51.556664,9.752744,60.717258,NaN,NaN,...,50.114029,35.0,3.876377,NaN,21.314995,8.201961,562.829529,14.170523,2.58,31.114035
2010-01-07 00:00:00,13.744131,5.022819,NaN,NaN,10.76,51.789165,9.617170,59.377014,NaN,NaN,...,50.263401,35.0,3.869143,NaN,21.314995,8.195896,639.046021,14.057959,2.80,30.752958
2010-01-08 00:00:00,14.482512,5.022819,NaN,NaN,10.82,52.131462,9.930681,60.148689,NaN,NaN,...,51.533054,33.5,3.881199,NaN,21.314995,8.222168,697.674072,13.945389,2.85,30.827898

In [6]:
# Fill NA with KNN
from fancyimpute import KNN
usa_market_filled = pd.DataFrame(KNN(k=3).fit_transform(usa_market), columns=usa_market.columns)
usa_market_filled.head()
usa_market_filled.isnull().sum()

Imputing row 1/3522 with 14 missing, elapsed time: 171.785
Imputing row 101/3522 with 0 missing, elapsed time: 171.796
Imputing row 201/3522 with 0 missing, elapsed time: 171.796
Imputing row 301/3522 with 0 missing, elapsed time: 171.796
Imputing row 401/3522 with 0 missing, elapsed time: 171.796
Imputing row 501/3522 with 0 missing, elapsed time: 171.796
Imputing row 601/3522 with 0 missing, elapsed time: 171.796
Imputing row 701/3522 with 0 missing, elapsed time: 171.796
Imputing row 801/3522 with 0 missing, elapsed time: 171.796
Imputing row 901/3522 with 0 missing, elapsed time: 171.796
Imputing row 1001/3522 with 0 missing, elapsed time: 171.796
Imputing row 1101/3522 with 0 missing, elapsed time: 171.796
Imputing row 1201/3522 with 0 missing, elapsed time: 171.796
Imputing row 1301/3522 with 0 missing, elapsed time: 171.796
Imputing row 1401/3522 with 0 missing, elapsed time: 171.796
Imputing row 1501/3522 with 0 missing, elapsed time: 171.796
Imputing row 1601/3522 with 0 missing, elapsed time: 171.796
Imputing row 1701/3522 with 0 missing, elapsed time: 171.796
Imputing row 1801/3522 with 0 missing, elapsed time: 171.796
Imputing row 1901/3522 with 0 missing, elapsed time: 171.796
Imputing row 2001/3522 with 0 missing, elapsed time: 171.796
Imputing row 2101/3522 with 0 missing, elapsed time: 171.796
Imputing row 2201/3522 with 0 missing, elapsed time: 171.796
Imputing row 2301/3522 with 0 missing, elapsed time: 171.796
Imputing row 2401/3522 with 0 missing, elapsed time: 171.796
Imputing row 2501/3522 with 0 missing, elapsed time: 171.796
Imputing row 2601/3522 with 0 missing, elapsed time: 171.796
Imputing row 2701/3522 with 0 missing, elapsed time: 171.796
Imputing row 2801/3522 with 0 missing, elapsed time: 171.811
Imputing row 2901/3522 with 0 missing, elapsed time: 171.811
Imputing row 3001/3522 with 0 missing, elapsed time: 171.812
Imputing row 3101/3522 with 0 missing, elapsed time: 171.813
Imputing row 3201/3522 with 0 missing, elapsed time: 171.813
Imputing row 3301/3522 with 0 missing, elapsed time: 171.814
Imputing row 3401/3522 with 0 missing, elapsed time: 171.815
Imputing row 3501/3522 with 7 missing, elapsed time: 171.816

AAL     0
AIR     0
AIRI    0
AIRT    0
ALGT    0
       ..
WCC     0
WLFC    0
WSO     0
WTRG    0
YORW    0
Length: 2440, dtype: int64

In [9]:
# Save filled data in real-data-treated
n,m = usa_market_filled.shape
yr = 2010
usa_market_filled.index = usa_market.index
usa_market_filled.to_csv(f'real-data-treated/usa_n{n}_m{m}_yr{yr}_filled.csv', index=True)

In [ ]:
usa_market_filled

In [3]:
# Read s&p500 data
sp500 = pd.read_csv('../real-data/s&p_n3522_yr2010.csv', index_col=0)
print(sp500.shape)
sp500.head()

(3522, 1)

            Adj Close
Date
2010-01-04  1132.9900
2010-01-05  1136.5200
2010-01-06  1137.1400
2010-01-07  1141.6899
2010-01-08  1144.9800